#!/bin/bash

set -e

if ! [[ -d "env" ]]; then
    ./setup.sh
fi

if [[ -n "$WINDIR" ]]; then
    BINDIR="env/Scripts"
else
    BINDIR="env/bin"
fi

# Setup dev dependencies if necessary
"$BINDIR/python" -m pytest --version || ./tests/env

"$BINDIR/python" -m pytest \
    --verbose --doctest-modules \
    --cov-config=setup.cfg --cov-report term-missing --cov=helloworld \
     helloworld/ tests/unittests/
